version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodejs-crud-service .
      - docker tag nodejs-crud-service:latest <account-id>.dkr.ecr.<region>.amazonaws.com/nodejs-crud-service:latest
      - echo Pushing Docker image to ECR...
      - docker push <account-id>.dkr.ecr.<region>.amazonaws.com/nodejs-crud-service:latest
  post_build:
    commands:
      - echo Deploying to Kubernetes...
      - kubectl apply -f deployment-green.yaml
      - kubectl apply -f service.yaml
artifacts:
  files:
    - deployment-green.yaml
    - service.yaml
